# Generated by Django 2.2.2 on 2019-06-29 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='class_name',
            new_name='classname',
        ),
    ]
